trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      terraform init
      terraform apply -auto-approve
    displayName: 'Deploy Infrastructure'

  - script: |
      ansible-playbook -i 172.174.72.168, playbook.yml -u azureuser --extra-vars "ansible_ssh_pass=Password1234!"
    displayName: 'Configure Server'

  - script: |
      docker build -t myapp .
      docker run -d -p 80:80 myapp
    displayName: 'Deploy Docker Container'
